"""empty message

Revision ID: 054a6378e064
Revises: 5c69a43687c0
Create Date: 2025-01-08 04:08:40.655574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '054a6378e064'
down_revision = '5c69a43687c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobposting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_workerid', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'worker', ['post_workerid'], ['worker_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobposting', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('post_workerid')

    # ### end Alembic commands ###
