"""empty message

Revision ID: 0a3efa979ad4
Revises: 49acee5fd7f2
Create Date: 2025-02-12 09:09:48.783759

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0a3efa979ad4'
down_revision = '49acee5fd7f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_status', sa.Enum('pending', 'paid', 'failed'), server_default='pending', nullable=False))
        batch_op.drop_column('pay_status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pay_status', mysql.ENUM('0', '1'), server_default=sa.text("'0'"), nullable=False))
        batch_op.drop_column('payment_status')

    # ### end Alembic commands ###
