"""empty message

Revision ID: 0feedacb7c91
Revises: c8807f83839c
Create Date: 2025-02-22 01:33:11.587387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0feedacb7c91'
down_revision = 'c8807f83839c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worker', schema=None) as batch_op:
        batch_op.add_column(sa.Column('worker_walletbalance', sa.Numeric(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worker', schema=None) as batch_op:
        batch_op.drop_column('worker_walletbalance')

    # ### end Alembic commands ###
