"""empty message

Revision ID: 2442cfa5581c
Revises: 053c82366c75
Create Date: 2025-02-10 15:05:44.465487

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2442cfa5581c'
down_revision = '053c82366c75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobposting', schema=None) as batch_op:
        batch_op.alter_column('post_status',
               existing_type=mysql.ENUM('0', '1'),
               nullable=False,
               existing_server_default=sa.text("'0'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobposting', schema=None) as batch_op:
        batch_op.alter_column('post_status',
               existing_type=mysql.ENUM('0', '1'),
               nullable=True,
               existing_server_default=sa.text("'0'"))

    # ### end Alembic commands ###
