"""empty message

Revision ID: 2833abfdaf16
Revises: 853dd897ce71
Create Date: 2025-03-01 12:10:28.123810

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2833abfdaf16'
down_revision = '853dd897ce71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('worker_recipient', schema=None) as batch_op:
        # batch_op.drop_index('recp_employerid')
        # batch_op.drop_constraint('worker_recipient_ibfk_2', type_='foreignkey')
        # batch_op.drop_column('recp_employerid')
        pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('worker_recipient', schema=None) as batch_op:
        # batch_op.add_column(sa.Column('recp_employerid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        # batch_op.create_foreign_key('worker_recipient_ibfk_2', 'employer', ['recp_employerid'], ['employer_id'])
        # batch_op.create_index('recp_employerid', ['recp_employerid'], unique=True)
        pass

    # ### end Alembic commands ###
