"""empty message

Revision ID: 29230dac2a88
Revises: 83117e82c8dc
Create Date: 2025-01-02 00:30:12.326226

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '29230dac2a88'
down_revision = '83117e82c8dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.alter_column('review_rating',
               existing_type=mysql.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.alter_column('review_rating',
               existing_type=mysql.FLOAT(),
               nullable=False)

    # ### end Alembic commands ###
