"""add unique constraint to category name

Revision ID: 402eaeacc7e9
Revises: 9e4c6cbb30cf
Create Date: 2026-04-05 07:02:28.367927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '402eaeacc7e9'
down_revision = '9e4c6cbb30cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['cat_name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
