"""empty message

Revision ID: 46d3e0c8a806
Revises: 054a6378e064
Create Date: 2025-01-09 23:13:12.888233

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '46d3e0c8a806'
down_revision = '054a6378e064'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobposting', schema=None) as batch_op:
        batch_op.alter_column('post_title',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('post_payrate',
               existing_type=mysql.DECIMAL(precision=10, scale=0),
               nullable=True)
        batch_op.alter_column('post_dateadded',
               existing_type=mysql.DATETIME(),
               nullable=True)
        batch_op.alter_column('post_closingdate',
               existing_type=mysql.DATETIME(),
               nullable=True)
        batch_op.alter_column('post_status',
               existing_type=mysql.ENUM('0', '1'),
               nullable=True,
               existing_server_default=sa.text("'0'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobposting', schema=None) as batch_op:
        batch_op.alter_column('post_status',
               existing_type=mysql.ENUM('0', '1'),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('post_closingdate',
               existing_type=mysql.DATETIME(),
               nullable=False)
        batch_op.alter_column('post_dateadded',
               existing_type=mysql.DATETIME(),
               nullable=False)
        batch_op.alter_column('post_payrate',
               existing_type=mysql.DECIMAL(precision=10, scale=0),
               nullable=False)
        batch_op.alter_column('post_title',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###
