"""empty message

Revision ID: 49acee5fd7f2
Revises: ec91b426329c
Create Date: 2025-02-11 15:35:32.619651

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '49acee5fd7f2'
down_revision = 'ec91b426329c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.alter_column('pay_date',
               existing_type=mysql.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.alter_column('pay_date',
               existing_type=mysql.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###
