"""empty message

Revision ID: 5106cc088459
Revises: 0a3efa979ad4
Create Date: 2025-02-12 09:10:43.658830

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5106cc088459'
down_revision = '0a3efa979ad4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pay_status', sa.Enum('pending', 'paid', 'failed'), server_default='pending', nullable=False))
        batch_op.drop_column('payment_status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_status', mysql.ENUM('pending', 'paid', 'failed'), server_default=sa.text("'pending'"), nullable=False))
        batch_op.drop_column('pay_status')

    # ### end Alembic commands ###
