"""empty message

Revision ID: 5c69a43687c0
Revises: 29230dac2a88
Create Date: 2025-01-04 04:20:20.557904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c69a43687c0'
down_revision = '29230dac2a88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worker', schema=None) as batch_op:
        batch_op.add_column(sa.Column('worker_categoryid', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'category', ['worker_categoryid'], ['cat_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worker', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('worker_categoryid')

    # ### end Alembic commands ###
