"""empty message

Revision ID: 62ce1f522091
Revises: 7a97a22d48dd
Create Date: 2025-02-19 18:57:21.901883

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '62ce1f522091'
down_revision = '7a97a22d48dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_constraint('review_ibfk_3', type_='foreignkey')
        batch_op.drop_column('review_jobid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('review_jobid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('review_ibfk_3', 'jobposting', ['review_jobid'], ['post_id'])

    # ### end Alembic commands ###
