"""empty message

Revision ID: 78ad7befca9b
Revises: 62ce1f522091
Create Date: 2025-02-19 18:59:32.319019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78ad7befca9b'
down_revision = '62ce1f522091'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('review_jobid', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'jobposting', ['review_jobid'], ['post_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('review_jobid')

    # ### end Alembic commands ###
