"""empty message

Revision ID: 7a97a22d48dd
Revises: c40f6dd8d0f9
Create Date: 2025-02-17 04:04:00.198801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a97a22d48dd'
down_revision = 'c40f6dd8d0f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        # batch_op.add_column(sa.Column('review_jobid', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'jobposting', ['review_jobid'], ['post_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('review_jobid')

    # ### end Alembic commands ###
