"""empty message

Revision ID: 83117e82c8dc
Revises: e92ca57404d5
Create Date: 2024-12-23 17:54:47.066844

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '83117e82c8dc'
down_revision = 'e92ca57404d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('experience', schema=None) as batch_op:
        batch_op.alter_column('exp_jobtitle',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('experience', schema=None) as batch_op:
        batch_op.alter_column('exp_jobtitle',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###
