"""empty message

Revision ID: 84c03cacd8dd
Revises: e12cac6721d5
Create Date: 2024-12-19 14:05:09.305948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84c03cacd8dd'
down_revision = 'e12cac6721d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worker', schema=None) as batch_op:
        batch_op.alter_column('worker_picture',
               existing_type=sa.BLOB(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worker', schema=None) as batch_op:
        batch_op.alter_column('worker_picture',
               existing_type=sa.BLOB(),
               nullable=False)

    # ### end Alembic commands ###
