"""empty message

Revision ID: 853dd897ce71
Revises: a6ee233361de
Create Date: 2025-03-01 11:57:43.716592

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '853dd897ce71'
down_revision = 'a6ee233361de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('worker_recipient', schema=None) as batch_op:
        # batch_op.drop_index('recp_employerid')
        # batch_op.drop_constraint('worker_recipient_ibfk_2', type_='foreignkey')
        # batch_op.drop_column('recp_employerid')
        pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('worker_recipient', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('recp_employerid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    #     batch_op.create_foreign_key('worker_recipient_ibfk_2', 'employer', ['recp_employerid'], ['employer_id'])
    #     batch_op.create_index('recp_employerid', ['recp_employerid'], unique=True)
    pass

    # ### end Alembic commands ###
