"""empty message

Revision ID: 90f5d2736987
Revises: 402eaeacc7e9
Create Date: 2026-05-03 05:53:46.886747

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '90f5d2736987'
down_revision = '402eaeacc7e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobapplication', schema=None) as batch_op:
        batch_op.drop_column('app_status')

    with op.batch_alter_table('worker', schema=None) as batch_op:
        batch_op.alter_column('worker_availability',
               existing_type=mysql.ENUM('0', '1'),
               type_=sa.Boolean(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('worker_verification',
               existing_type=mysql.ENUM('0', '1'),
               type_=sa.Boolean(),
               nullable=True,
               existing_server_default=sa.text("'0'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worker', schema=None) as batch_op:
        batch_op.alter_column('worker_verification',
               existing_type=sa.Boolean(),
               type_=mysql.ENUM('0', '1'),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('worker_availability',
               existing_type=sa.Boolean(),
               type_=mysql.ENUM('0', '1'),
               nullable=False,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('jobapplication', schema=None) as batch_op:
        batch_op.add_column(sa.Column('app_status', mysql.ENUM('0', '1'), server_default=sa.text("'0'"), nullable=False))

    # ### end Alembic commands ###
