"""empty message

Revision ID: 928d2de4c420
Revises: b08f51c85a3f
Create Date: 2025-03-06 00:18:53.329609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '928d2de4c420'
down_revision = 'b08f51c85a3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('withdrawal',
    sa.Column('withdraw_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('withdraw_userid', sa.Integer(), nullable=False),
    sa.Column('withdraw_usertype', sa.String(length=100), nullable=False),
    sa.Column('withdraw_amount', sa.Numeric(), nullable=False),
    sa.Column('withdraw_status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('withdraw_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('withdrawal')
    # ### end Alembic commands ###
