"""empty message

Revision ID: 9bca96eb172d
Revises: 81cd7342941e
Create Date: 2025-02-24 13:53:39.756377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bca96eb172d'
down_revision = '81cd7342941e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employer_walletbalance', sa.Numeric(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employer', schema=None) as batch_op:
        batch_op.drop_column('employer_walletbalance')

    # ### end Alembic commands ###
