"""empty message

Revision ID: a0e29b850b47
Revises: 9bca96eb172d
Create Date: 2025-02-25 03:20:02.659166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0e29b850b47'
down_revision = '9bca96eb172d'
branch_labels = None
depends_on = None


def upgrade():
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('worker_recipient', schema=None) as batch_op:
        # batch_op.add_column(sa.Column('recp_employerid', sa.Integer(), nullable=False))
        # batch_op.create_unique_constraint(None, ['recp_employerid'])
        # batch_op.create_foreign_key(None, 'employer', ['recp_employerid'], ['employer_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('worker_recipient', schema=None) as batch_op:
        # batch_op.drop_constraint(None, type_='foreignkey')
        # batch_op.drop_constraint(None, type_='unique')
        # batch_op.drop_column('recp_employerid')
        pass

    # ### end Alembic commands ###
