"""empty message

Revision ID: a6ee233361de
Revises: ca292477b4bb
Create Date: 2025-03-01 11:42:49.579797

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a6ee233361de'
down_revision = 'ca292477b4bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('employer_recipient',
    # sa.Column('emprecp_id', sa.Integer(), autoincrement=True, nullable=False),
    # sa.Column('emprecp_employerid', sa.Integer(), nullable=False),
    # sa.Column('emprecp_code', sa.String(length=100), nullable=True),
    # sa.Column('emprecp_createdat', sa.DateTime(), nullable=True),
    # sa.Column('emprecp_bankaccount_name', sa.String(length=100), nullable=False),
    # sa.Column('emprecp_bank_number', sa.String(length=20), nullable=False),
    # sa.Column('emprecp_bank_code', sa.String(length=10), nullable=False),
    # sa.ForeignKeyConstraint(['emprecp_employerid'], ['employer.employer_id'], ),
    # sa.PrimaryKeyConstraint('emprecp_id'),
    # sa.UniqueConstraint('emprecp_employerid')
    # )
    # with op.batch_alter_table('worker_recipient', schema=None) as batch_op:
    #     batch_op.drop_index('recp_employerid')
    #     batch_op.drop_constraint('worker_recipient_ibfk_2', type_='foreignkey')
    #     batch_op.drop_column('recp_employerid')
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('worker_recipient', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('recp_employerid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    #     batch_op.create_foreign_key('worker_recipient_ibfk_2', 'employer', ['recp_employerid'], ['employer_id'])
    #     batch_op.create_index('recp_employerid', ['recp_employerid'], unique=True)

    # op.drop_table('employer_recipient')
    pass
    # ### end Alembic commands ###
