"""empty message

Revision ID: b08f51c85a3f
Revises: 2833abfdaf16
Create Date: 2025-03-01 12:39:33.745577

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b08f51c85a3f'
down_revision = '2833abfdaf16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
     with op.batch_alter_table('worker_recipient', schema=None) as batch_op:
         batch_op.drop_index('recp_employerid')
         batch_op.drop_constraint('worker_recipient_ibfk_2', type_='foreignkey')
         batch_op.drop_column('recp_employerid')
    

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worker_recipient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recp_employerid', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('worker_recipient_ibfk_2', 'employer', ['recp_employerid'], ['employer_id'])
        batch_op.create_index('recp_employerid', ['recp_employerid'], unique=True)

    

    # ### end Alembic commands ###
