"""empty message

Revision ID: c8807f83839c
Revises: d2aa4eb523d1
Create Date: 2025-02-21 04:05:54.288784

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c8807f83839c'
down_revision = 'd2aa4eb523d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worker_recipient', schema=None) as batch_op:
        batch_op.alter_column('recp_code',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worker_recipient', schema=None) as batch_op:
        batch_op.alter_column('recp_code',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###
