"""empty message

Revision ID: ca292477b4bb
Revises: a0e29b850b47
Create Date: 2025-02-25 03:48:37.804542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca292477b4bb'
down_revision = 'a0e29b850b47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('worker_recipient', schema=None) as batch_op:
        # batch_op.create_foreign_key(None, 'employer', ['recp_employerid'], ['employer_id'])
        pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('worker_recipient', schema=None) as batch_op:
    #     batch_op.drop_constraint(None, type_='foreignkey')
    pass

    # ### end Alembic commands ###
