"""empty message

Revision ID: d2aa4eb523d1
Revises: ba1a922cda5f
Create Date: 2025-02-20 22:09:34.518389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2aa4eb523d1'
down_revision = 'ba1a922cda5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worker_recipient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recp_bankaccount_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('recp_bank_number', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('recp_bank_code', sa.String(length=10), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worker_recipient', schema=None) as batch_op:
        batch_op.drop_column('recp_bank_code')
        batch_op.drop_column('recp_bank_number')
        batch_op.drop_column('recp_bankaccount_name')

    # ### end Alembic commands ###
