"""empty message

Revision ID: d70ebab01259
Revises: 2442cfa5581c
Create Date: 2025-02-11 12:52:31.168269

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd70ebab01259'
down_revision = '2442cfa5581c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pay_workerid', sa.Integer(), nullable=True))
        batch_op.drop_constraint('payment_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'worker', ['pay_workerid'], ['worker_id'])
        batch_op.drop_column('pay_appid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pay_appid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('payment_ibfk_1', 'worker', ['pay_appid'], ['worker_id'])
        batch_op.drop_column('pay_workerid')

    # ### end Alembic commands ###
