"""empty message

Revision ID: e12cac6721d5
Revises: 948133f6cab2
Create Date: 2024-12-19 14:04:00.090271

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e12cac6721d5'
down_revision = '948133f6cab2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worker', schema=None) as batch_op:
        batch_op.alter_column('worker_gender',
               existing_type=mysql.VARCHAR(length=45),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worker', schema=None) as batch_op:
        batch_op.alter_column('worker_gender',
               existing_type=mysql.VARCHAR(length=45),
               nullable=False)

    # ### end Alembic commands ###
