"""empty message

Revision ID: e42a9c19d38e
Revises: 84c03cacd8dd
Create Date: 2024-12-22 09:53:07.892747

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e42a9c19d38e'
down_revision = '84c03cacd8dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('experience', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exp_about', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('exp_years', sa.String(length=50), nullable=False))
        batch_op.drop_column('exp_enddate')
        batch_op.drop_column('exp_startdate')

    with op.batch_alter_table('worker', schema=None) as batch_op:
        batch_op.add_column(sa.Column('worker_stateid', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'state', ['worker_stateid'], ['state_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worker', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('worker_stateid')

    with op.batch_alter_table('experience', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exp_startdate', mysql.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('exp_enddate', mysql.DATETIME(), nullable=False))
        batch_op.drop_column('exp_years')
        batch_op.drop_column('exp_about')

    # ### end Alembic commands ###
