"""empty message

Revision ID: e92ca57404d5
Revises: e42a9c19d38e
Create Date: 2024-12-23 17:16:53.223727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e92ca57404d5'
down_revision = 'e42a9c19d38e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employer', schema=None) as batch_op:
        batch_op.alter_column('employer_picture',
               existing_type=sa.BLOB(),
               type_=sa.String(length=100),
               existing_nullable=True)

    with op.batch_alter_table('experience', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exp_picture', sa.String(length=100), nullable=True))

    with op.batch_alter_table('worker', schema=None) as batch_op:
        batch_op.alter_column('worker_picture',
               existing_type=sa.BLOB(),
               type_=sa.String(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worker', schema=None) as batch_op:
        batch_op.alter_column('worker_picture',
               existing_type=sa.String(length=100),
               type_=sa.BLOB(),
               existing_nullable=True)

    with op.batch_alter_table('experience', schema=None) as batch_op:
        batch_op.drop_column('exp_picture')

    with op.batch_alter_table('employer', schema=None) as batch_op:
        batch_op.alter_column('employer_picture',
               existing_type=sa.String(length=100),
               type_=sa.BLOB(),
               existing_nullable=True)

    # ### end Alembic commands ###
